baseURL = "/"
title = "Tal Glanzman"
theme = "bootstrap"

# copyright = "Copyright © 2016-{year} Razon Yang. All Rights Reserved." >> This is the theme writer. Also see the "powered by"
comment = false

# Multilingual mode
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true # If you use only one language comment this option

# Pagination
paginate = 5
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
