email = "talglanzman@gmail.com"
github = "tglanz"
linkedin = "in/tal-glanzman"
stackoverflow = "7924529"
dockerhub = "talglanzman"
codepen = "tglanz"

# facebook = "yourfacebookusername"
# gitlab = "yourgitlabusername"
# twitter = "yourtwitterusername"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
# instagram = "yourinstagramusername"
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# bitbucket = "yourbitbucketworkspaceid"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
