name: Github Pages
run-name: "Github Pages: ${{ github.event.head_commit.message }}"

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    name: Build and Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: personal-site 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: personal-site/package-lock.json
    - name: Build the site
      run: |
        npm install
        npm run build
        touch out/.nojekyll
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: personal-site/out
