# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and deploy the site at out/ to github pages (gh-pages branch)
name: Github Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: |
        npm install
        npm run build
        npm run export
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
