name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build jekyll in container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && bundle install && jekyll build -s src/ -d site/ --future && mv site/* /srv/jekyll"
    - name: postmortem
      if: ${{ failure() || success() }}
      run: |
        echo "finding: ${{ github.workspace }}" && find ${{ github.workspace }}